# File: tests/test_gdbmerge_instantiation.py
# Generated by JetBrains AI with Nick Santos review

from unbox.compile_gdbs import GDBMerge


def test_gdbmerge_instantiation():
    """
    Test that the GDBMerge class can be instantiated properly
    """
    gdb_merge = GDBMerge(
        input_folder="path/to/input",
        output_gdb_path="path/to/output.gdb",
        temp_folder="path/to/temp"
    )
    assert gdb_merge.input_folder == "path/to/input"
    assert gdb_merge.output_gdb_path == "path/to/output.gdb"
    assert gdb_merge.temp_folder == "path/to/temp"

def test_gdbmerge_default_tempfolder():
    """
    Test that the GDBMerge class assigns a default temp folder
    when none is provided.
    """
    gdb_merge = GDBMerge(
        input_folder="path/to/input",
        output_gdb_path="path/to/output.gdb"
    )
    assert gdb_merge.temp_folder is not None
    assert "lightbox_merge_" in gdb_merge.temp_folder


def test_gdbmerge_extract_zips_flag():
    """
    Test the effect of setting the extract_zips flag
    during instantiation.
    """
    gdb_merge_true = GDBMerge(
        input_folder="path/to/input",
        output_gdb_path="path/to/output.gdb",
        extract_zips=True
    )
    gdb_merge_false = GDBMerge(
        input_folder="path/to/input",
        output_gdb_path="path/to/output.gdb",
        extract_zips=False
    )
    assert gdb_merge_true.extract_zips is True
    assert gdb_merge_false.extract_zips is False


def test_gdbmerge_setup_logging():
    """
    Test that the setup_logging flag can be set during instantiation.
    """
    gdb_merge = GDBMerge(
        input_folder="path/to/input",
        output_gdb_path="path/to/output.gdb",
        setup_logging=True
    )
    # Check that setup_logging does not affect other attributes
    assert gdb_merge.input_folder == "path/to/input"
    assert gdb_merge.output_gdb_path == "path/to/output.gdb"
